### ISSUE TITLE
compile with downloaded libraries

### ISSUE THREAD

**Issue by richipower** [imistyrain/ssd#2]
Hello,

i am trying to get this version working on my pc, unfortunately i get errors with the script because i am under a proxy and i am not able to get cmake through it, i downloaded the dependencies from caffe_builder and i would like to know if is possible to modify the cmake file to skip the downloading part and read directly from the downloaded files but i am getting problems getting it to work.. could you orient me a little bit? where should i make changes? have you tried bilding it without internet, or locally?
i am trying with some modifications on the WindowsDownloadPrebuiltDependencies.cmake but no success, many thanks for any tips!!
thank you! 

greets

**Comment by imistyrain** [comment]
Of course you can. Just download libraries_v140_x64_py27_1.1.0.tar.bz2(or libraries_v140_x64_py35_1.1.0.tar.bz2 if you are using python3,the link is in [Baidu Yun](https://pan.baidu.com/s/19mYgT7V7jgmRu_1ILRrhdg) and password for download it：it2a), and put it into C:\Users\lenovo\.caffe\dependencies\download,where lenovo should be the name of your computer. Note there is a dot the path, where you cann't create it with the normal way, but use the console cmd by "mkdir .caffe".

**Comment by richipower** [comment]
hello! thank you for the fast response!, i will try to see if i get it working :)

**Comment by richipower** [comment]
hello @imistyrain, i succesfully build it for CPU_ONLY, and it works perfectly thanks!, now i am trying to build it for CUDA and i get an error:

**C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code -1073741701.** 

Have you experienced something similar? or any ideas what could be going wrong?
i have CUDA 9 and CUDNN 7.1.2. CMake outputs are both correct, configuration and generation.. and on the build_win.cmd i just added this lines at the beginning:

**set BUILD_PYTHON=0
set BUILD_PYTHON_LAYER=0
set CPU_ONLY=0**

Do you have any ideas or hints of what i could be doing wrong? or what i can change?

regards and thanks!

**Comment by imistyrain** [comment]
The information above cannot give any useful clues. You don't have to do any changes for the build_win.cmd because the default setting is to use CUDA and CUDNN.

**Comment by richipower** [comment]
yes, i just modified - build_win.cmd - to build without python. I am not sure if that has to do with my CUDA and CUDNN version, could you tell me on which configuration are you running it?

**Comment by imistyrain** [comment]
OK.I used CUDA 8.0 and cudnn6.0, also build with python layer.Both Win7 and Win10 is tested.

**Comment by richipower** [comment]
aaaaa i seee yes maybe thats the difference, i will try to see if i can link it to CUDA 8, do you have maybe the compiled caffe library that you can share?

**Comment by imistyrain** [comment]
The compiled library is too big to upload. What's your [WeChat](https://www.wechat.com/en/) number or do you have a [QQ](https://im.qq.com/)? or [TeamViewer](https://www.teamviewer.com/en/) ID, I can give you a remote control help.

**Comment by richipower** [comment]
hello! sorry i just got to my pc.. i just downloaded wechat.. +4917645609934 i cannot use the other two :(
